# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: application build and push
      run: |
        gradle clean jib --image youthconpso/hello:latest \
        -Djib.to.auth.username=${{ secrets.DUSER }} \
        -Djib.to.auth.password=${{ secrets.DPWD }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    # https://github.com/marketplace/actions/setup-kustomize
    - name: setup kustomize
      uses: imranismail/setup-kustomize@v1

    # https://github.com/actions/checkout
    - name: checkout config repo
      uses: actions/checkout@v2
      with: 
        repository: sang5c/demo-youthcon-21-config
        token: ${{ secrets.ACCESS_TOKEN }}
        path: test-path
    
    - name: config commit and push
      run: |
          cd test-path
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update image"
          git push
