# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: build and push
      run: ./hello-app/gradlew clean jib --image youthconpso/hello:latest \                                                                                                                                ✔  38s  00:06:18 
            -Djib.to.auth.username=${{secrets.DUSER}} \
            -Djib.to.auth.password=${{secrets.DPWD}}

#     - name: Build with Gradle
#       uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
#       with:
#         arguments: build
